//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMDbContext : DbContext
    {
        public CRMDbContext()
            : base("name=CRMDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<XOX_T_ACCNT_ATT> XOX_T_ACCNT_ATT { get; set; }
        public virtual DbSet<XOX_T_ACCNT_NOTE> XOX_T_ACCNT_NOTE { get; set; }
        public virtual DbSet<XOX_T_ASSET_CON> XOX_T_ASSET_CON { get; set; }
        public virtual DbSet<XOX_T_ASSET_OM> XOX_T_ASSET_OM { get; set; }
        public virtual DbSet<XOX_T_AUDIT_LOG> XOX_T_AUDIT_LOG { get; set; }
        public virtual DbSet<XOX_T_AUDIT_TRAIL> XOX_T_AUDIT_TRAIL { get; set; }
        public virtual DbSet<XOX_T_CON_ACCNT> XOX_T_CON_ACCNT { get; set; }
        public virtual DbSet<XOX_T_CON_ADDR> XOX_T_CON_ADDR { get; set; }
        public virtual DbSet<XOX_T_CONTACT> XOX_T_CONTACT { get; set; }
        public virtual DbSet<XOX_T_DEMAND_LST> XOX_T_DEMAND_LST { get; set; }
        public virtual DbSet<XOX_T_GROUP> XOX_T_GROUP { get; set; }
        public virtual DbSet<XOX_T_GROUP_ACCESS> XOX_T_GROUP_ACCESS { get; set; }
        public virtual DbSet<XOX_T_LKP_GENERAL> XOX_T_LKP_GENERAL { get; set; }
        public virtual DbSet<XOX_T_MODULE> XOX_T_MODULE { get; set; }
        public virtual DbSet<XOX_T_ORDER> XOX_T_ORDER { get; set; }
        public virtual DbSet<XOX_T_ORDER_ATT> XOX_T_ORDER_ATT { get; set; }
        public virtual DbSet<XOX_T_ORDER_ITEM_OM> XOX_T_ORDER_ITEM_OM { get; set; }
        public virtual DbSet<XOX_T_ORDER_NOTE> XOX_T_ORDER_NOTE { get; set; }
        public virtual DbSet<XOX_T_PROD_ATTR> XOX_T_PROD_ATTR { get; set; }
        public virtual DbSet<XOX_T_PROD_ISP> XOX_T_PROD_ISP { get; set; }
        public virtual DbSet<XOX_T_PROD_ITEM> XOX_T_PROD_ITEM { get; set; }
        public virtual DbSet<XOX_T_PROD_OM> XOX_T_PROD_OM { get; set; }
        public virtual DbSet<XOX_T_SRV_ACT> XOX_T_SRV_ACT { get; set; }
        public virtual DbSet<XOX_T_SRV_ATT> XOX_T_SRV_ATT { get; set; }
        public virtual DbSet<XOX_T_SRV_KEYVAL> XOX_T_SRV_KEYVAL { get; set; }
        public virtual DbSet<XOX_T_SRV_NOTE> XOX_T_SRV_NOTE { get; set; }
        public virtual DbSet<XOX_T_SRV_TIC> XOX_T_SRV_TIC { get; set; }
        public virtual DbSet<XOX_T_USER_GROUP> XOX_T_USER_GROUP { get; set; }
        public virtual DbSet<XOX_T_USER_GROUP_DEPT> XOX_T_USER_GROUP_DEPT { get; set; }
        public virtual DbSet<XOX_T_VAL_LST> XOX_T_VAL_LST { get; set; }
        public virtual DbSet<XOX_T_VAL_MST> XOX_T_VAL_MST { get; set; }
        public virtual DbSet<XOX_T_ACCNT_BANK> XOX_T_ACCNT_BANK { get; set; }
        public virtual DbSet<XOX_T_IS_KEY> XOX_T_IS_KEY { get; set; }
        public virtual DbSet<XOX_T_ACCNT_ACT> XOX_T_ACCNT_ACT { get; set; }
        public virtual DbSet<XOX_T_ACCNT_REV> XOX_T_ACCNT_REV { get; set; }
        public virtual DbSet<XOX_T_REV_NUM> XOX_T_REV_NUM { get; set; }
        public virtual DbSet<XOX_T_ORDER_ITEM> XOX_T_ORDER_ITEM { get; set; }
        public virtual DbSet<XOX_T_USER> XOX_T_USER { get; set; }
        public virtual DbSet<XOX_T_ADDR> XOX_T_ADDR { get; set; }
        public virtual DbSet<XOX_T_PROD> XOX_T_PROD { get; set; }
        public virtual DbSet<XOX_T_ASSET> XOX_T_ASSET { get; set; }
        public virtual DbSet<XOX_T_ACCNT> XOX_T_ACCNT { get; set; }
        public virtual DbSet<XOX_T_ORDER_AUDIT> XOX_T_ORDER_AUDIT { get; set; }
        public virtual DbSet<XOX_T_ORDER_ACT> XOX_T_ORDER_ACT { get; set; }
        public virtual DbSet<XOX_T_ACCNT_PAYMENT> XOX_T_ACCNT_PAYMENT { get; set; }
        public virtual DbSet<XOX_T_BATCHWORK_LOG> XOX_T_BATCHWORK_LOG { get; set; }
        public virtual DbSet<XOX_T_BATCHWORK> XOX_T_BATCHWORK { get; set; }
        public virtual DbSet<XOX_T_BILL_PAYMENT> XOX_T_BILL_PAYMENT { get; set; }
        public virtual DbSet<XOX_T_ACCNT_REFUND> XOX_T_ACCNT_REFUND { get; set; }
        public virtual DbSet<XOX_T_PAYMENT_COLLECTED> XOX_T_PAYMENT_COLLECTED { get; set; }
        public virtual DbSet<XOX_T_BATCHWORK_EMAIL> XOX_T_BATCHWORK_EMAIL { get; set; }
    }
}
