//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_DEMAND_LST
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public string DL_NUM { get; set; }
        public string DL_CUST_NAME { get; set; }
        public string DL_ADDR_TYPE { get; set; }
        public string DL_ADDR { get; set; }
        public string DL_ADDR_1 { get; set; }
        public string DL_ADDR_2 { get; set; }
        public string DL_BUILDING_NAME { get; set; }
        public string DL_STREET_TYPE { get; set; }
        public string DL_STREET_NAME { get; set; }
        public string DL_SECTION { get; set; }
        public string DL_POSTAL_CD { get; set; }
        public string DL_CITY { get; set; }
        public string DL_STATE { get; set; }
        public string DL_COUNTRY { get; set; }
        public string DL_STATUS { get; set; }
        public string DL_SOURCE { get; set; }
        public string DL_REASON { get; set; }
        public string DL_COMMENT { get; set; }
        public string DL_EMAIL { get; set; }
        public string DL_CONTACT_NUM { get; set; }
        public Nullable<long> DL_PROD_ID { get; set; }
    }
}
