//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_BATCHWORK
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public Nullable<System.DateTime> START_AT { get; set; }
        public Nullable<System.DateTime> END_AT { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> RUN_SEQUENCE { get; set; }
        public Nullable<long> FREQUENCY { get; set; }
        public Nullable<long> TEMP_FREQUENCY { get; set; }
        public Nullable<bool> FLG_SEND_EMAIL_NOTIF { get; set; }
    }
}
