//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_ACCNT_BANK
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public Nullable<long> CUST_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_ACCNT_NO { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string CREDIT_CARD_NO { get; set; }
        public string CREDIT_CARD_SALT { get; set; }
        public string CREDIT_CARD_ISSUER { get; set; }
        public string CREDIT_CARD_HOLDER { get; set; }
        public Nullable<int> CREDIT_CARD_EXPIRY_MONTH { get; set; }
        public Nullable<int> CREDIT_CARD_EXPIRY_YEAR { get; set; }
        public Nullable<bool> THIRD_PARTY_FLG { get; set; }
    }
}
