//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_PAYMENT_COLLECTED
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> PAYMENT_ID { get; set; }
        public string MSISDN { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> CHARGE_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATE { get; set; }
        public string METHOD { get; set; }
    }
}
