//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_BILL_PAYMENT
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public Nullable<long> ACCNT_ID { get; set; }
        public string BILL_CYCLE { get; set; }
        public string SUBMISSION_DATE { get; set; }
        public string MSISDN { get; set; }
        public string POSTPAID_PLAN { get; set; }
        public Nullable<decimal> AMOUNT_DUE { get; set; }
        public string CREDIT_CARD { get; set; }
        public string SUBSCRIBER_NAME { get; set; }
        public string COMPANY_NAME { get; set; }
        public string CVV { get; set; }
        public Nullable<int> CARD_EXPIRY_MONTH { get; set; }
        public Nullable<int> CARD_EXPIRY_YEAR { get; set; }
        public Nullable<int> PAYMENT_STATUS { get; set; }
        public string REMARKS { get; set; }
        public string BANK_ISSUER { get; set; }
    
        public virtual XOX_T_ACCNT XOX_T_ACCNT { get; set; }
    }
}
