//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_IS_KEY
    {
        public long ROW_ID { get; set; }
        public string API_KEY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public Nullable<long> XOX_IS_ID { get; set; }
    }
}
