//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_USER
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string STAFF_NAME { get; set; }
        public string USER_TYPE { get; set; }
        public string ACTIVE_FLG { get; set; }
        public Nullable<long> CUST_ID { get; set; }
        public Nullable<int> LOGIN_FAILED_ATTEMPT { get; set; }
    }
}
