//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_ASSET
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public string ASSET_NUM { get; set; }
        public Nullable<long> PROD_ID { get; set; }
        public string STATUS_CD { get; set; }
        public Nullable<long> CUST_ID { get; set; }
        public Nullable<long> BILL_ID { get; set; }
        public Nullable<long> SVC_AC_ID { get; set; }
        public Nullable<long> PAR_ASSET_ID { get; set; }
        public Nullable<long> ROOT_ASSET_ID { get; set; }
        public string SERVICE_NUM { get; set; }
        public string INTEGRATION_ID { get; set; }
        public Nullable<System.DateTime> INSTALL_DT { get; set; }
        public Nullable<System.DateTime> END_DT { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<decimal> PAID_AMOUNT { get; set; }
    }
}
