//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_CONTACT
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public string PERSON_UID { get; set; }
        public string DEFAULT_FLG { get; set; }
        public string CONTACT_FLG { get; set; }
        public string SALUTATION { get; set; }
        public string FST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string ID_TYPE { get; set; }
        public string ID_NUM { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTH_DT { get; set; }
        public string NATIONALITY { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string MOBILE_NO { get; set; }
        public string HOUSE_NO { get; set; }
        public string OFFICE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string POSTN { get; set; }
        public string INTEGRATION_ID { get; set; }
    }
}
