//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_PROD
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public string PRD_NAME { get; set; }
        public string PRD_DESC { get; set; }
        public string PRD_CATEGORY { get; set; }
        public string PRD_TYPE { get; set; }
        public string PRD_LVL { get; set; }
        public string PRD_CURRENCY { get; set; }
        public Nullable<decimal> PRD_PRICE { get; set; }
        public string PRD_PRICE_TYPE { get; set; }
        public Nullable<long> PROVIDER_ID { get; set; }
        public string QUOTA { get; set; }
        public string DL_SPD { get; set; }
        public string UL_SPD { get; set; }
        public Nullable<int> CONT_TERM { get; set; }
        public string CON_PERIOD { get; set; }
        public string POLICY { get; set; }
        public string IMAGE_FILE_PATH { get; set; }
        public string ACTIVE_FLG { get; set; }
        public string SEGMENT_TYPE { get; set; }
        public string PART_NUM { get; set; }
        public string INTEGRATION_ID { get; set; }
        public string EXT_PROD_NAME { get; set; }
        public Nullable<int> MAX_QTY { get; set; }
        public string VIS_ASSET { get; set; }
        public string VIS_INVOICE { get; set; }
        public string VAS_FLG { get; set; }
        public string SVC_ID_REQ { get; set; }
        public string EQ_ID_REQ { get; set; }
        public string PWD_REQ { get; set; }
        public string PROVI_REQ { get; set; }
        public string GST_CD { get; set; }
        public Nullable<int> GST_PT { get; set; }
        public string INV_GROUP { get; set; }
        public string OTC_FLG { get; set; }
        public string DISPLAY_FLG { get; set; }
    }
}
