//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_ACCNT_PAYMENT
    {
        public long ROW_ID { get; set; }
        public long ACCNT_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string REFERENCE { get; set; }
        public string PAYMENT_STATUS { get; set; }
        public string RECEIPT_NUM { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string BANK_ISSUER { get; set; }
        public string CARD_TYPE { get; set; }
        public string CARD_NUMBER { get; set; }
        public string CARD_EXPIRY_DATE { get; set; }
        public Nullable<bool> FLAG_RESPONSE { get; set; }
    }
}
