//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_SRV_TIC
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public long SR_NUM { get; set; }
        public Nullable<long> CUST_ID { get; set; }
        public Nullable<long> ASSET_ID { get; set; }
        public string CATEGORY { get; set; }
        public string SUB_CATEGORY { get; set; }
        public string PRIORITY { get; set; }
        public string STATUS_CD { get; set; }
        public Nullable<long> CASE_OWNER_ID { get; set; }
        public Nullable<System.DateTime> CASE_DUE_DT { get; set; }
        public string TEAM { get; set; }
        public string ASSIGNEE { get; set; }
        public Nullable<System.DateTime> CASE_RESL_DT { get; set; }
        public string RESOLUTION { get; set; }
        public string RES_TYPE { get; set; }
        public string CASE_DESC { get; set; }
        public string BILL_ACCNT_NUM { get; set; }
        public string INV_NUM { get; set; }
        public Nullable<decimal> DISPUTE_AMT { get; set; }
        public string CHQ_NUM { get; set; }
        public string CUST_COMP_FLG { get; set; }
        public string SVC_TYPE { get; set; }
        public string SVC_NUM { get; set; }
        public string NEW_ADR_UNIT { get; set; }
        public string NEW_ADR_FLR { get; set; }
        public string NEW_ADR_BLDG { get; set; }
        public string NEW_ADR_STREET { get; set; }
        public string NEW_ADR_SCT { get; set; }
        public string NEW_ADR_POST { get; set; }
        public string NEW_ADR_CITY { get; set; }
        public string NEW_ADR_STATE { get; set; }
        public string NEW_ADR_CTY { get; set; }
        public string NEW_CON_NUM { get; set; }
        public string NEW_CON_NAME { get; set; }
        public string NEW_CON_EMAIL { get; set; }
        public string NEW_PYMT_MET { get; set; }
        public string NEW_BILL_TYPE { get; set; }
        public string BILL_AJST_RSN { get; set; }
        public string NEW_CON_MSISDN { get; set; }
        public Nullable<decimal> NEW_CREDIT_LIMIT { get; set; }
        public string OLD_CON_NUM { get; set; }
        public string OLD_ACCNT_PROFILE { get; set; }
        public string NEW_ACCNT_PROFILE { get; set; }
        public Nullable<decimal> OLD_CREDIT_LIMIT { get; set; }
    }
}
