//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOX.CRM.Lib.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOX_T_ADDR
    {
        public long ROW_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> LAST_UPD_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD { get; set; }
        public string ADDR_NAME { get; set; }
        public string ADDR_TYPE { get; set; }
        public string ADDR { get; set; }
        public string ADDR_1 { get; set; }
        public string ADDR_2 { get; set; }
        public string BUILDING_NAME { get; set; }
        public string STREET_TYPE { get; set; }
        public string STREET_NAME { get; set; }
        public string SECTION { get; set; }
        public string POSTAL_CD { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string INTEGRATION_ID { get; set; }
        public string SITE_NAME { get; set; }
        public Nullable<System.DateTime> APPT_DT { get; set; }
        public string STATUS_CD { get; set; }
    }
}
