insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ANDORRA','1', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'UNITED ARAB EMIRATES','2', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ANTIGUA & BARBUDA','3', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ANGUILLA','4', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ALBANIA','5', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ARMENIA','6', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NETHERLANDS ANTILLES','7', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ANGOLA','8', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'AZORES','9', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ARGENTINA','10', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'AMERICAN SAMOA','11', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'AUSTRIA','12', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'AUSTRALIA','13', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ARUBA','14', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'AZERBAIJAN','15', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BOSNIA','16', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BARBADOS','17', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BANGLADESH','18', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BELGIUM','19', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BURKINA FASO','20', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BULGARIA','21', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BAHRAIN','22', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BURUNDI','23', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BENIN','24', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BONAIRE','25', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BERMUDA','26', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BRUNEI','27', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BOLIVIA','28', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BRAZIL','29', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BAHAMAS','30', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BOTSWANA','31', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BELARUS','32', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BELIZE','33', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CANADA','34', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CURACAO','35', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CENTRAL AFRICAN REPUBLIC','36', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CONGO','37', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SWITZERLAND','38', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'COTE D''IVOIRE (IVORY COAST)','39', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'COOK ISLAND','40', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CHILE','41', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CAMEROON','42', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CHINA','43', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'COLOMBIA','44', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'COSTA RICA','45', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CAPE VERDE','46', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CYPRUS','47', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CZECH REPUBLIC','48', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GERMANY','49', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'DJIBOUTI','50', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'DENMARK','51', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'DOMINICA','52', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'DOMINICAN REPUBLIC','53', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ALGERIA','54', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ECUADOR','55', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ESTONIA','56', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'EGYPT','57', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ENGLAND','58', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ERITREA','59', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SPAIN','60', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ETHIOPIA','61', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. EUSTATIUS','62', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'FINLAND','63', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'FIJI','64', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MICRONESIA','65', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'FAEROE ISLANDS','66', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'FRANCE','67', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GABON','68', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'UNITED KINGDOM','69', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GRENADA','70', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GEORGIA','71', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'FRENCH GUIANA','72', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GUERNSEY','73', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GHANA','74', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GIBRALTAR','75', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GREENLAND','76', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GAMBIA','77', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GUINEA','78', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GUADELOUPE','79', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'EQUATORIAL GUINEA','80', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GREECE','81', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GUATEMALA','82', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GUAM','83', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GUINEA-BISSAU','84', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'GUYANA','85', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'HONG KONG','86', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'HONDURAS','87', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'HOLLAND','88', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CROATIA','89', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'HAITI','90', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'HUNGARY','91', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CANARY ISLANDS','92', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'INDONESIA','93', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'IRELAND','94', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ISRAEL','95', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'INDIA','96', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ICELAND','97', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ITALY','98', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'JERSEY','99', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'JAMAICA','100', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'JORDAN','101', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'JAPAN','102', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'KENYA','103', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'KYRGYZSTAN','104', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CAMBODIA','105', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'KIRIBATI','106', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. KITTS & NEVIS','107', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'KOSRAE','108', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SOUTH KOREA','109', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'KUWAIT','110', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CAYMAN ISLANDS','111', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'KAZAKHSTAN','112', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LAOS','113', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LEBANON','114', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. LUCIA','115', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LIECHTENSTEIN','116', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SRI LANKA','117', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LIBERIA','118', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LESOTHO','119', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LITHUANA','120', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LUXEMBOURG','121', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LATVIA','122', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MOROCCO','123', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. MAARTEN','124', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MONACO','125', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MOLDOVA','126', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MADEIRA','127', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MADAGASCAR','128', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MARSHALL ISLANDS','129', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MACEDONIA','130', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MALI','131', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MONGOLIA','132', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MACAU','133', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'N. MARIANA ISLANDS','134', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MARTINIQUE','135', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MAURITANIA','136', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MONTSERRAT','137', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MALTA','138', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MAURITIUS','139', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MALDIVES','140', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MALAWI','141', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MEXICO','142', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MALAYSIA','143', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MOZAMBIQUE','144', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NAMIBIA','145', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NORTHERN IRELAND','146', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NEW CALEDONIA','147', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NIGER','148', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NORFOLK ISLAND','149', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NIGERIA','150', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NICARAGUA','151', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NETHERLANDS','152', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NORWAY','153', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NEPAL','154', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST.BARTHELEMY','155', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'NEW ZEALAND','156', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'OMAN','157', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PANAMA','158', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PERU','159', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'FRENCH POLYNESIA','160', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PAPUA NEW GUINEA','161', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PHILIPPINES','162', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PAKISTAN','163', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'POLAND','164', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PONAPE','165', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PUERTO RICO','166', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PORTUGAL','167', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PALAU','168', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'PARAGUAY','169', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'QATAR','170', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'REUNION','171', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ROMANIA','172', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ROTA','173', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'RUSSIA','174', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'RWANDA','175', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SAUDI ARABIA','176', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SOLOMAN ISLANDS','177', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SEYCHELLES','178', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SWEDEN','179', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SCOTLAND','180', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SINGAPORE','181', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SLOVENIA','182', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SLOVAKIA','183', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SIERRA LEONE','184', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SAN MARINO','185', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SENEGAL','186', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SAIPAN','187', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SURINAME','188', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SABA','189', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'EL SALVADOR','190', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. CHRISTOPHER','191', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. CROIX','192', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SYRIA','193', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SWAZILAND','194', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TAHITI','195', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. MARTIN','196', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TURKS & CAICOS ISLANDS','197', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'CHAD','198', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TOGO','199', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'THAILAND','200', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TINIAN','201', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TAJIKISTAN','202', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TORTOLA','203', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TURKMENISTAN','204', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TUNISIA','205', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TONGA','206', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TURKEY','207', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TRINIDAD & TOBAGO','208', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TRUK','209', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TUVALU','210', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TAIWAN','211', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'TANZANIA','212', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'UKRAINE','213', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'UGANDA','214', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'UNION ISLAND','215', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'UNITED STATES','216', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. JOHN','217', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'URUGUAY','218', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'UZBEKISTAN','219', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'VATICAN CITY STATE','220', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. VINCENT/GRENADINE','221', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'VENEZUELA','222', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'BRITISH VIRGIN ISLES','223', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'US VIRGIN ISLANDS','224', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ST. THOMAS','225', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'VIETNAM','226', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'VIRGIN GORDA','227', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'VANUATU','228', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'WALLIS & FUTUNA ISLANDS','229', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'WALES','230', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'WESTERN SAMOA','231', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'YAP','232', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'YEMEN','233', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'YUGOSLAVIA','234', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SOUTH AFRICA','235', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ZAMBIA','236', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'ZIMBABWE','237', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SUDAN','238', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'LIBYA','239', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'MYANMAR','240', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'IRAQ','241', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'Nationality', 'SERBIA','242', 1, 1)
