INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Maybank', N'Maybank', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Public Bank', N'Public Bank', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Affin Islamic Bank Berhad', N'Affin Islamic Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Alliance Islamic Bank Berhad', N'Alliance Islamic Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'AmIslamic Bank Berhad', N'AmIslamic Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Asian Finance Bank Berhad', N'Asian Finance Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bank Islam Malaysia Berhad', N'Bank Islam Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bank Muamalat Malaysia Berhad', N'Bank Muamalat Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'CIMB Islamic Bank Berhad', N'CIMB Islamic Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'HSBC Amanah Malaysia Berhad', N'HSBC Amanah Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Hong Leong Islamic Bank Berhad', N'Hong Leong Islamic Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Kuwait Finance House (Malaysia) Berhad', N'Kuwait Finance House (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Maybank Islamic Berhad', N'Maybank Islamic Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'OCBC Al-Amin Bank Berhad', N'OCBC Al-Amin Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Public Islamic Bank Berhad', N'Public Islamic Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'RHB Islamic Bank Berhad', N'RHB Islamic Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Standard Chartered Saadiq Berhad', N'Standard Chartered Saadiq Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Affin Bank Berhad', N'Affin Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Alliance Bank Malaysia Berhad', N'Alliance Bank Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'AmBank (M) Berhad', N'AmBank (M) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'BNP Paribas Malaysia Berhad', N'BNP Paribas Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bangkok Bank Berhad', N'Bangkok Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bank of America Malaysia Berhad', N'Bank of America Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bank of China (Malaysia) Berhad', N'Bank of China (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bank of Tokyo-Mitsubishi UFJ (Malaysia) Berhad', N'Bank of Tokyo-Mitsubishi UFJ (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'CIMB Bank Berhad', N'CIMB Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Citibank Berhad', N'Citibank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Deutsche Bank (Malaysia) Berhad', N'Deutsche Bank (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'HSBC Bank Malaysia Berhad', N'HSBC Bank Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Hong Leong Bank Berhad', N'Hong Leong Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'India International Bank (Malaysia) Berhad', N'India International Bank (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Industrial and Commercial Bank of China (Malaysia) Berhad', N'Industrial and Commercial Bank of China (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'J.P. Morgan Chase Bank Berhad', N'J.P. Morgan Chase Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Mizuho Bank (Malaysia) Berhad', N'Mizuho Bank (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'National Bank of Abu Dhabi Malaysia Berhad', N'National Bank of Abu Dhabi Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'OCBC Bank (Malaysia) Berhad', N'OCBC Bank (Malaysia) Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'RHB Bank Berhad', N'RHB Bank Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Standard Chartered Bank Malaysia Berhad', N'Standard Chartered Bank Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Sumitomo Mitsui Banking Corporation Malaysia Berhad', N'Sumitomo Mitsui Banking Corporation Malaysia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'The Bank of Nova Scotia Berhad', N'The Bank of Nova Scotia Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'The Royal Bank of Scotland Berhad', N'The Royal Bank of Scotland Berhad', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'United Overseas Bank (Malaysia) Bhd.', N'United Overseas Bank (Malaysia) Bhd.', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bank Simpanan National', N'Bank Simpanan National', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Bank Rakyat', N'Bank Rakyat', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'AEON', N'AEON', 1, N'1', NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Bank Name', N'Agro Bank', N'Agro Bank', 1, N'1', NULL)
