INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Race Mapping', N'1',N'Malay',1,N'1',NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Race Mapping', N'2',N'Chinese',1,N'1',NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Race Mapping', N'3',N'Others',1,N'1',NULL)
INSERT [XOX_T_VAL_LST] ([TYPE], [NAME], [VAL], [SEQUENCE], [ACTIVE_FLG], [PAR_VAL_ID]) VALUES (N'Race Mapping', N'4',N'Indian',1,N'1',NULL)
