insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Selangor','SELANGOR', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Kuala Lumpur','KUALA LUMPUR', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Putrajaya','PUTRAJAYA', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Penang','PENANG', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Kedah','KEDAH', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Perlis','PERLIS', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Perak','PERAK', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Negeri Sembilan','NEGERI SEMBILAN', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Melaka','MELAKA', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Johor','JOHOR', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Sabah','SABAH', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Sarawak','SARAWAK', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Labuan','LABUAN', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Kelantan','KELANTAN', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Pahang','PAHANG', 1, 1)
insert into xox_t_val_lst (created_by,created, type, name, val, SEQUENCE, ACTIVE_FLG) values (1, getdate(), 'States', 'Terengganu','TERENGGANU', 1, 1)
