INSERT INTO [dbo].[XOX_T_GROUP] ([CREATED],[GROUP_CD],[ACTIVE_FLG]) VALUES(getdate(),'Admin','1')


SET IDENTITY_INSERT [dbo].[XOX_T_MODULE] ON 
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (1, NULL, NULL, N'Account', N'Account', 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (2, NULL, NULL, N'Product', N'Product', 1, 1, 1, 1, 1, 1)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (3, NULL, NULL, N'Service', N'Service', 1, 1, 1, 1, 1, 1)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (4, NULL, NULL, N'UserAccess', N'User Access Control', 1, 1, 1, 1, 1, 1)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (5, NULL, NULL, N'User', N'User', 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (6, NULL, NULL, N'Group', N'User Group', 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (7, NULL, NULL, N'Module', N'Module Access', 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (8, NULL, NULL, N'MobileNum', N'Mobile Number Management', 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (9, NULL, NULL, N'Lookup', N'Lookup', 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_MODULE] ([ROW_ID], [CREATED_BY], [CREATED], [MODULE_CD], [MODULE_NM], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (10, NULL, NULL, N'Order', N'Order', 1, 1, 1, 1, 1, 1)
GO
SET IDENTITY_INSERT [dbo].[XOX_T_MODULE] OFF
GO


SET IDENTITY_INSERT [dbo].[XOX_T_GROUP_ACCESS] ON 
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (1, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (2, NULL, NULL, NULL, NULL, 1, 2, 1, 1, 1, 1, 1, 1)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (3, NULL, NULL, NULL, NULL, 1, 3, 1, 1, 1, 1, 1, 1)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (4, NULL, NULL, NULL, NULL, 1, 4, 1, 1, 1, 1, 1, 1)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (5, NULL, NULL, NULL, NULL, 1, 5, 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (6, NULL, NULL, NULL, NULL, 1, 6, 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (7, NULL, NULL, NULL, NULL, 1, 7, 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (8, NULL, NULL, NULL, NULL, 1, 8, 1, 1, 1, 0, 0, 0)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (9, NULL, NULL, NULL, NULL, 1, 9, 1, 1, 1, 1, 0, 0)
GO
INSERT [dbo].[XOX_T_GROUP_ACCESS] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [GROUP_ID], [MODULE_ID], [IS_VIEWABLE], [IS_ADDABLE], [IS_EDITABLE], [IS_DELETABLE], [IS_APPROVABLE], [IS_REJECTABLE]) VALUES (10, NULL, NULL, NULL, NULL, 1, 10, 1, 1, 1, 1, 1, 1)
GO
SET IDENTITY_INSERT [dbo].[XOX_T_GROUP_ACCESS] OFF
GO


SET IDENTITY_INSERT [dbo].[XOX_T_USER] ON 
GO
INSERT [dbo].[XOX_T_USER] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [USERNAME], [PASSWORD], [STAFF_NAME], [USER_TYPE], [ACTIVE_FLG], [CUST_ID]) VALUES (1, NULL, NULL, 1, NULL, N'abc@abc.com', N'123456', N'Admin', NULL, N'1', NULL)
GO
SET IDENTITY_INSERT [dbo].[XOX_T_USER] OFF
GO


SET IDENTITY_INSERT [dbo].[XOX_T_USER_GROUP] ON 
GO
INSERT [dbo].[XOX_T_USER_GROUP] ([ROW_ID], [CREATED_BY], [CREATED], [LAST_UPD_BY], [LAST_UPD], [USER_ID], [GROUP_ID]) VALUES (1, NULL, NULL, NULL, NULL, 1, 1)
GO
SET IDENTITY_INSERT [dbo].[XOX_T_USER_GROUP] OFF
GO

