alter table [XOX_T_ACCNT_PAYMENT]
add ADVANCE_PAYMENT decimal(18,0)

EXEC sp_rename 'XOX_T_ACCNT_PAYMENT.AMOUNT', 'DEPOSIT', 'COLUMN'


/////

EXEC sp_rename 'XOX_T_ACCNT_PAYMENT.DEPOSIT', 'AMOUNT', 'COLUMN'

alter table XOX_T_ACCNT_PAYMENT
DROP COLUMN ADVANCE_PAYMENT

alter table [XOX_T_ACCNT_PAYMENT]
add PAYMENT_TYPE nvarchar(255)