alter table [XOX_T_ORDER_ACT]
add ORDER_STATUS nvarchar(30)

EXEC sp_RENAME 'XOX_T_ACCNT.OLD_CUSTOMER_NUM' , 'SIM_SERIAL_NUMBER', 'COLUMN'
EXEC sp_RENAME 'XOX_T_ACCNT.INDUSTRIAL_CD' , 'DEALER_CODE', 'COLUMN'

alter table [XOX_T_ACCNT]
add BANK_ACCNT_NAME nvarchar(max)