ALTER TABLE [XOX_T_ADDR]
ALTER COLUMN [ADDR_1] nvarchar(MAX) NULL

ALTER TABLE [XOX_T_ADDR]
ALTER COLUMN [ADDR_2] nvarchar(MAX) NULL

ALTER TABLE [XOX_T_ADDR]
ALTER COLUMN [ADDR] nvarchar(MAX) NULL

ALTER TABLE [XOX_T_ADDR]
ALTER COLUMN [STATE] nvarchar(100) NULL

DROP INDEX [XOX_T_ACCNT_U01] ON [XOX_T_ACCNT]