
--XOX_T_PAYMENT_COLLECTED
DROP TABLE XOX_T_PAYMENT_COLLECTED

CREATE TABLE XOX_T_PAYMENT_COLLECTED
(
 ROW_ID BIGINT IDENTITY(1,1) NOT NULL
,CREATED_BY	BIGINT
,CREATED DATETIME
,
[PAYMENT_ID] [bigint] NULL,
[MSISDN] NVARCHAR(20) NULL,
[AMOUNT] DECIMAL(18,4) NULL,
[CHARGE_TYPE] [int] NULL,
[DESCRIPTION] [nvarchar](max) NULL,
[PAYMENT_DATE] [DATETIME] NULL,
[METHOD] [nvarchar](255) NULL,


 CONSTRAINT XOX_T_PAYMENT_COLLECTED_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)
)