--XOX_T_BATCHWORK_EMAIL
DROP TABLE XOX_T_BATCHWORK_EMAIL

CREATE TABLE XOX_T_BATCHWORK_EMAIL
(
 ROW_ID BIGINT IDENTITY(1,1) NOT NULL
,CREATED_BY	BIGINT
,CREATED DATETIME
,
[BATCHWORK_ID] [bigint] NULL,
[EMAIL] NVARCHAR(50) NULL,


 CONSTRAINT XOX_T_BATCHWORK_EMAIL_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)
)