
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POP00001','XOX Postpaid Pro 158','Postpaid','Principal','MOLI','MYR','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'XOX Postpaid Pro 158',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POP00002','XOX Postpaid Ultra 108','Postpaid','Principal','MOLI','MYR','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'XOX Postpaid Ultra 108',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POP00003','XOX Postpaid Super 58','Postpaid','Principal','MOLI','MYR','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'XOX Postpaid Super 58',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POP00004','XOX Postpaid Supp 18','Postpaid','Supplementary','MOLI','MYR','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'XOX Postpaid Supp 18',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00001','24 Months Contract','Postpaid','Features','OLI','MYR','0',NULL,NULL,NULL,NULL,NULL,NULL,'24',NULL,NULL,'Y',NULL,NULL,NULL,'24 Months Contract',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00002','Monthly Rebate RM 8','Postpaid','Features','OLI','MYR','8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Monthly Rebate RM 8',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00003','Monthly Rebate RM 0','Postpaid','Features','OLI','MYR','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Monthly Rebate RM 0',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00004','Pro 158 Charges','Postpaid','Features','OLI','MYR','150','Recurring',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Pro 158 Charges',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00005','Ultra 108 Charges','Postpaid','Features','OLI','MYR','100','Recurring',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Ultra 108 Charges',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00006','Super 58 Charges','Postpaid','Features','OLI','MYR','50','Recurring',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Super 58 Charges',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00007','Supp 18 Charges','Postpaid','Features','OLI','MYR','18','Recurring',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Supp 18 Charges',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00008','4G LTE Internet Quota 4.5GB','Postpaid','Features','OLI','MYR','0',NULL,NULL,'4.5 GB',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'4G LTE Internet Quota 4.5GB',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00009','4G LTE Internet Quota 3.5GB','Postpaid','Features','OLI','MYR','0',NULL,NULL,'3.5 GB',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'4G LTE Internet Quota 3.5GB',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00010','4G LTE Internet Quota 1GB','Postpaid','Features','OLI','MYR','0',NULL,NULL,'1 GB',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'4G LTE Internet Quota 1GB',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00011','4G LTE Internet Quota 250MB','Postpaid','Features','OLI','MYR','0',NULL,NULL,'250 MB',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'4G LTE Internet Quota 250MB',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00012','400 Mins Calls','Postpaid','Features','OLI','MYR','0',NULL,NULL,'400 Mins',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'400 Mins Calls',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00013','250 Mins Calls','Postpaid','Features','OLI','MYR','0',NULL,NULL,'250 Mins',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'250 Mins Calls',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00014','150 Mins Calls','Postpaid','Features','OLI','MYR','0',NULL,NULL,'150 Mins',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'150 Mins Calls',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00015','100 Mins Calls','Postpaid','Features','OLI','MYR','0',NULL,NULL,'100 Mins',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'100 Mins Calls',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00016','120 Mins Closed User Group','Postpaid','Features','OLI','MYR','0',NULL,NULL,'120 Mins',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'120 Mins Closed User Group',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00017','60 Mins Closed User Group','Postpaid','Features','OLI','MYR','0',NULL,NULL,'60 Mins',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'60 Mins Closed User Group',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00018','300 SMS','Postpaid','Features','OLI','MYR','0',NULL,NULL,'300 SMS',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'300 SMS',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00019','150 SMS','Postpaid','Features','OLI','MYR','0',NULL,NULL,'150 SMS',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'150 SMS',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00020','100 SMS','Postpaid','Features','OLI','MYR','0',NULL,NULL,'100 SMS',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'100 SMS',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'AOD00001','Auto Data Add-On','Postpaid','Addon','MOLI','MYR','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Auto Data Add-On',NULL,'Y',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'AOD00002','Add-On 4G Internet 500MB','Postpaid','Addon Features','OLI','MYR','0',NULL,NULL,'500 MB',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Add-On 4G Internet 500MB',NULL,'Y',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'AOD00003','Add-On Free 30 Mins','Postpaid','Addon Features','OLI','MYR','0',NULL,NULL,'30 Mins',NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Add-On Free 30 Mins',NULL,'Y',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'AOD00004','Add-On Charges','Postpaid','Addon Features','OLI','MYR','18','Recurring',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,'Add-On Charges',NULL,'Y',NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00021','International Roaming','Postpaid','VAS','OLI','MYR','300','One Time',null,null,null,null,null,null,null,null,'Y',null,null,null,'International Roaming',null,'Y',null,'Y',null,null,null,null,null,null,null,null,null)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00022','Printed Billing','Postpaid','VAS','OLI','MYR','5','Recurring',null,null,null,null,null,null,null,null,'Y',null,null,null,'Printed Billing',null,'Y',null,'Y',null,null,null,null,null,null,null,null,null)
insert into XOX_T_PROD values (1,getdate(),1,getdate(),'POL00023','Foreigner Deposit','Postpaid','VAS','OLI','MYR','500','One Time',null,null,null,null,null,null,null,null,'Y',null,null,null,'Foreigner Deposit',null,'Y',null,'Y',null,null,null,null,null,null,null,null,null)



insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','1',NULL,'1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','5','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','6','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','8','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','12','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','16','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','20','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','22','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','25','1','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','26','9','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','27','9','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','28','9','1','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','2',NULL,'13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','5','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','6','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','9','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','13','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','17','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','21','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','23','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','25','13','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','26','21','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','27','21','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','28','21','13','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','3',NULL,'25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','5','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','6','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','10','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','14','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','18','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','21','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','24','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','25','25','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','26','33','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','27','33','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','28','33','25','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','4',NULL,'37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','5','37','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','7','37','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','11','37','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','15','37','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','19','37','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','25','37','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','26','43','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','27','43','37','Y',NULL,NULL,NULL)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'4','28','43','37','Y',NULL,NULL,NULL)

insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','29','1','1','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','30','1','1','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'1','31','1','1','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','29','13','13','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','30','13','13','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'2','31','13','13','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','29','25','25','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','30','25','25','Y',null,null,null)
insert into xox_t_prod_item values (1,getdate(),1,getdate(),'3','31','25','25','Y',null,null,null)



select b.prod_item_id, b.row_id, b.par_item_id, b.root_item_id, a.prd_desc, a.vas_flg, a.prd_lvl, a.prd_price, a.prd_category, a.prd_type, a.prd_price_type, a.quota
from xox_t_prod a
inner join xox_t_prod_item b on b.prod_id = a.row_id