
--XOX_T_ACCNT
DROP TABLE XOX_T_ACCNT

CREATE TABLE XOX_T_ACCNT
(
 ROW_ID BIGINT IDENTITY(1,1) NOT NULL
,CREATED_BY	BIGINT
,CREATED DATETIME
,LAST_UPD_BY BIGINT
,LAST_UPD DATETIME
,NAME NVARCHAR(100)  NOT NULL
,LOC NVARCHAR(30)
,BIRTH_DT DATETIME
,SALUTATION	NVARCHAR(30)
,NATIONALITY NVARCHAR(30)
,ID_TYPE NVARCHAR(30)
,ID_NUM	NVARCHAR(50)
,CUST_TYPE_CD NVARCHAR(30)
,ACCNT_TYPE_CD NVARCHAR(30) NOT NULL
,INTEGRATION_ID NVARCHAR(30)
,CUSTOMER_NUM NVARCHAR(30)
,ACCNT_STATUS NVARCHAR(30)
,ADDR_ID BIGINT
,EMAIL_ADDR NVARCHAR(100)
,MOBILE_NO NVARCHAR(30)
,HOUSE_NO NVARCHAR(30)
,OFFICE_NO NVARCHAR(30)
,FAX_NO	NVARCHAR(30)
,MOTHER_MAIDEN_NAME NVARCHAR(255)
,BILL_CYCLE	NVARCHAR(10)
,BILL_CURR NVARCHAR(10)
,BILL_LANG NVARCHAR(30)
,PAYMENT_METHOD NVARCHAR(30)
,BANK_NAME VARCHAR(50)
,CUST_SINCE	DATE
,PAR_ACCNT_ID BIGINT
,MASTER_ACCNT_ID BIGINT
,CONTACT_NAME NVARCHAR(250)
,BUSINESS_TYPE NVARCHAR(30)
,WEBSITE_URL NVARCHAR(255)
,EMP_NO	INT
,VIP_FLG NVARCHAR(30)
,BILL_ACCNT_NUM NVARCHAR(30)
,BILL_ACCNT_NAME NVARCHAR(100)
,BILL_COMP_NAME NVARCHAR(100)
,SALES_CD NVARCHAR(30)
,INDUSTRIAL_CD NVARCHAR(30)
,OLD_CUSTOMER_NUM NVARCHAR(30)
,CUST_USER_ID	BIGINT
,ACCNT_SUB_STATUS NVARCHAR(30)
,CREDIT_LIMIT DECIMAL(18,2)
 CONSTRAINT XOX_T_ACCNT_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)
)

CREATE INDEX XOX_T_ACCNT_F01 ON XOX_T_ACCNT (ADDR_ID)
CREATE INDEX XOX_T_ACCNT_F02 ON XOX_T_ACCNT (PAR_ACCNT_ID)
CREATE INDEX XOX_T_ACCNT_F03 ON XOX_T_ACCNT (MASTER_ACCNT_ID)

CREATE UNIQUE INDEX XOX_T_ACCNT_U01 ON XOX_T_ACCNT (NAME, LOC)

CREATE INDEX XOX_T_ACCNT_M01 ON XOX_T_ACCNT (INTEGRATION_ID)
CREATE INDEX XOX_T_ACCNT_M02 ON XOX_T_ACCNT (CUST_TYPE_CD)
CREATE INDEX XOX_T_ACCNT_M03 ON XOX_T_ACCNT (ACCNT_TYPE_CD)
CREATE INDEX XOX_T_ACCNT_M04 ON XOX_T_ACCNT (ACCNT_STATUS)
CREATE INDEX XOX_T_ACCNT_M05 ON XOX_T_ACCNT (BILL_ACCNT_NUM)
