
--XOX_T_BATCHWORK_LOG
DROP TABLE XOX_T_BATCHWORK_LOG

CREATE TABLE XOX_T_BATCHWORK_LOG
(
 ROW_ID BIGINT IDENTITY(1,1) NOT NULL
,CREATED_BY	BIGINT
,CREATED DATETIME

,BATCHWORK_ID BIGINT
,DESCRIPTION NVARCHAR(MAX)


 CONSTRAINT XOX_T_BATCHWORK_LOG_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)
)
