--DROP TABLE XOX_T_BILL_PAYMENT

CREATE TABLE XOX_T_BILL_PAYMENT
(
 ROW_ID BIGINT IDENTITY(1,1) NOT NULL
,CREATED_BY BIGINT
,CREATED DATETIME
,LAST_UPD_BY BIGINT
,LAST_UPD DATETIME
,ACCNT_ID BIGINT
,BILL_CYCLE VARCHAR(10)
,SUBMISSION_DATE VARCHAR(10)
,MSISDN VARCHAR(20)
,POSTPAID_PLAN VARCHAR(50)
,AMOUNT_DUE DECIMAL(18,2)
,CREDIT_CARD VARCHAR(30)
,SUBSCRIBER_NAME VARCHAR(100)
,COMPANY_NAME VARCHAR(50)
,CVV VARCHAR(20)
,CARD_EXPIRY_MONTH INT
,CARD_EXPIRY_YEAR INT
,PAYMENT_STATUS INT
,REMARKS VARCHAR(255)
 CONSTRAINT XOX_T_BILL_PAYMENT_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)
CONSTRAINT FK_BILL_PAYMENT_ACCNT FOREIGN KEY (ACCNT_ID) REFERENCES XOX_T_ACCNT(ROW_ID)
)

CREATE INDEX XOX_T_BILL_PAYMENT_U01 ON XOX_T_BILL_PAYMENT (ACCNT_ID)
