--XOX_T_ACCNT_PAYMENT
DROP TABLE XOX_T_ACCNT_PAYMENT

CREATE TABLE XOX_T_ACCNT_PAYMENT
(
	ROW_ID BIGINT IDENTITY(1,1) NOT NULL,
	ACCNT_ID bigint NOT NULL,
	AMOUNT decimal NOT NULL,
	REFERENCE nvarchar(200),
	PAYMENT_STATUS nvarchar(200),
	RECEIPT_NUM nvarchar(200),
	CREATED_BY BIGINT,
	CREATED DATETIME,
	LAST_UPD_BY BIGINT,
	LAST_UPD DATETIME
	CONSTRAINT XOX_T_ACCNT_PAYMENT_P01 PRIMARY KEY CLUSTERED 
	(
		ROW_ID
	)
)
